[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,--no-relax",
]
target = "xtensa-esp32s3-none-elf"
