[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor -L defmt"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,--no-relax",
  "-C", "link-arg=-Tdefmt.x",
]
target = "xtensa-esp32s3-none-elf"